name: 'medalists_all_2024'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medalists_all_2024:
    bronze:
      +materialized: table
      +database: "{{ 'BRONZE_DB_PRO' if target.name == 'pro' else 'BRONZE_DB_DEV' }}"

    silver:
      +materialized: table
      +transient: false
      +database: "{{ 'SILVER_DB_PRO' if target.name == 'pro' else 'SILVER_DB_DEV' }}"

    gold:
      +materialized: table
      +transient: false
      +database: "{{ 'GOLD_DB_PRO' if target.name == 'pro' else 'GOLD_DB_DEV' }}"