table FACT_MEDALLA
	lineageTag: 642e41f5-def4-42b3-9105-2404ba140d3f

	column ID_MEDALLA
		dataType: string
		lineageTag: 8a958da8-206d-4c9c-87e1-b617b23af1de
		summarizeBy: none
		sourceColumn: ID_MEDALLA

		annotation SummarizationSetBy = Automatic

	column TIPO_MEDALLA
		dataType: string
		lineageTag: de08ed42-8096-4dd6-ab2d-011aa16f0d5c
		summarizeBy: none
		sourceColumn: TIPO_MEDALLA

		annotation SummarizationSetBy = Automatic

	column ID_ATLETA
		dataType: string
		lineageTag: 4d41e85d-92fd-44c8-b028-98f13ad9072f
		summarizeBy: none
		sourceColumn: ID_ATLETA

		annotation SummarizationSetBy = Automatic

	column NOMBRE_ATLETA
		dataType: string
		lineageTag: 22f91386-6b72-47d8-b9f7-6f4a3b35643d
		summarizeBy: none
		sourceColumn: NOMBRE_ATLETA

		annotation SummarizationSetBy = Automatic

	column FECHA_NACIMIENTO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2e8bb7da-0b7b-4695-92a3-00391f3492c4
		summarizeBy: none
		sourceColumn: FECHA_NACIMIENTO

		variation Variación
			isDefault
			relationship: 701afcfc-d77c-4083-82e1-205531d597c4
			defaultHierarchy: LocalDateTable_a7d23a13-7035-4040-b388-f94879c613d1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SEXO
		dataType: string
		lineageTag: 0e85ff2a-619a-4291-afc3-33a06038f77e
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column LUGAR_NACIMIENTO
		dataType: string
		lineageTag: f14b6424-cc02-4070-a3cf-d64ebbaeda1e
		summarizeBy: none
		sourceColumn: LUGAR_NACIMIENTO

		annotation SummarizationSetBy = Automatic

	column REGION_NACIMIENTO
		dataType: string
		lineageTag: 1bb4af83-29c3-41c7-8b4e-4bd49acfb133
		summarizeBy: none
		sourceColumn: REGION_NACIMIENTO

		annotation SummarizationSetBy = Automatic

	column LAT_NACIMIENTO
		dataType: double
		lineageTag: 77344fef-95fe-4e27-ad15-a1dc08b6364e
		summarizeBy: average
		sourceColumn: LAT_NACIMIENTO

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LON_NACIMIENTO
		dataType: double
		lineageTag: d33440a4-e2c9-4238-86de-7d234b7c1607
		summarizeBy: average
		sourceColumn: LON_NACIMIENTO

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_PAIS
		dataType: string
		lineageTag: 6ead803f-f05a-4d68-9d87-dddcd17f8882
		summarizeBy: none
		sourceColumn: ID_PAIS

		annotation SummarizationSetBy = Automatic

	column NOMBRE_PAIS
		dataType: string
		lineageTag: 9213c291-76ac-4427-9b0a-610c13f6fe06
		summarizeBy: none
		sourceColumn: NOMBRE_PAIS

		annotation SummarizationSetBy = Automatic

	column CODIGO_ISO2_PAIS
		dataType: string
		lineageTag: d648149e-c2dd-4277-9814-595bcb0e5f39
		summarizeBy: none
		sourceColumn: CODIGO_ISO2_PAIS

		annotation SummarizationSetBy = Automatic

	column CODIGO_ISO3_PAIS
		dataType: string
		lineageTag: 24e7941a-5d23-4a31-9047-99c400a548c1
		summarizeBy: none
		sourceColumn: CODIGO_ISO3_PAIS

		annotation SummarizationSetBy = Automatic

	column CODIGO_COI_PAIS
		dataType: string
		lineageTag: dd4f929d-b535-47eb-9834-50a88627bed9
		summarizeBy: none
		sourceColumn: CODIGO_COI_PAIS

		annotation SummarizationSetBy = Automatic

	column ID_DELEGACION
		dataType: string
		lineageTag: d8c58d65-d80f-4c32-8c91-84f395860c4d
		summarizeBy: none
		sourceColumn: ID_DELEGACION

		annotation SummarizationSetBy = Automatic

	column NOMBRE_DELEGACION
		dataType: string
		lineageTag: cbdc7954-cad9-4bce-b747-3fb9d98284b0
		summarizeBy: none
		sourceColumn: NOMBRE_DELEGACION

		annotation SummarizationSetBy = Automatic

	column ID_EVENTO
		dataType: string
		lineageTag: b2d4d40f-e0cc-4034-9cf6-fe28d7056a53
		summarizeBy: none
		sourceColumn: ID_EVENTO

		annotation SummarizationSetBy = Automatic

	column NOMBRE_EVENTO
		dataType: string
		lineageTag: 0e7838f8-b09b-4193-8d54-de7c02e023ff
		summarizeBy: none
		sourceColumn: NOMBRE_EVENTO

		annotation SummarizationSetBy = Automatic

	column NOMBRE_DISCIPLINA
		dataType: string
		lineageTag: 8d71183e-2c50-4764-9114-d929da12f34e
		summarizeBy: none
		sourceColumn: NOMBRE_DISCIPLINA

		annotation SummarizationSetBy = Automatic

	column NOMBRE_DEPORTE
		dataType: string
		lineageTag: c09c8c44-10f5-4d16-b29c-2c25c07b5872
		summarizeBy: none
		sourceColumn: NOMBRE_DEPORTE

		annotation SummarizationSetBy = Automatic

	column ID_NUTS3
		dataType: string
		lineageTag: 8245c190-738d-4252-aca1-bd447a10d385
		summarizeBy: none
		sourceColumn: ID_NUTS3

		annotation SummarizationSetBy = Automatic

	column NOMBRE_NUTS3
		dataType: string
		lineageTag: 8e30d6cb-d93d-4df0-8f15-2449ef93946a
		summarizeBy: none
		sourceColumn: NOMBRE_NUTS3

		annotation SummarizationSetBy = Automatic

	column ID_NUTS2
		dataType: string
		lineageTag: 65451b61-7ee6-46e4-ac4a-42f598f60264
		summarizeBy: none
		sourceColumn: ID_NUTS2

		annotation SummarizationSetBy = Automatic

	column NOMBRE_NUTS2
		dataType: string
		lineageTag: f782ee08-5dea-4c06-8ceb-8aa6c5c3ed8f
		summarizeBy: none
		sourceColumn: NOMBRE_NUTS2

		annotation SummarizationSetBy = Automatic

	column ID_NUTS1
		dataType: string
		lineageTag: 5989aa37-6155-4bda-98b7-f81f5120229f
		summarizeBy: none
		sourceColumn: ID_NUTS1

		annotation SummarizationSetBy = Automatic

	column NOMBRE_NUTS1
		dataType: string
		lineageTag: 35bb84f2-2522-4639-a62b-e5de1c312fcc
		summarizeBy: none
		sourceColumn: NOMBRE_NUTS1

		annotation SummarizationSetBy = Automatic

	column ID_NUTS0
		dataType: string
		lineageTag: 5b150b9b-2339-403b-921f-061da5f2c414
		summarizeBy: none
		sourceColumn: ID_NUTS0

		annotation SummarizationSetBy = Automatic

	column NOMBRE_PAIS_NUTS
		dataType: string
		lineageTag: e055dc63-5eee-4bce-825d-fa271c0ac070
		summarizeBy: none
		sourceColumn: NOMBRE_PAIS_NUTS

		annotation SummarizationSetBy = Automatic

	column EDAD
		dataType: int64
		lineageTag: aa000001-0000-0000-0000-000000000011
		summarizeBy: average
		expression = YEAR(DATE(2024, 7, 26)) - YEAR([FECHA_NACIMIENTO])

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Medallas' = COUNTROWS(FACT_MEDALLA)
		formatString: "#,##0"
		lineageTag: aa000001-0000-0000-0000-000000000001
		displayFolder: KPIs

	measure 'Medallistas Únicos' = DISTINCTCOUNT(FACT_MEDALLA[ID_ATLETA])
		formatString: "#,##0"
		lineageTag: aa000001-0000-0000-0000-000000000002
		displayFolder: KPIs

	measure 'Países Representados' = DISTINCTCOUNT(FACT_MEDALLA[NOMBRE_PAIS])
		formatString: "#,##0"
		lineageTag: aa000001-0000-0000-0000-000000000003
		displayFolder: KPIs

	measure 'Deportes Únicos' = DISTINCTCOUNT(FACT_MEDALLA[NOMBRE_DEPORTE])
		formatString: "#,##0"
		lineageTag: aa000001-0000-0000-0000-000000000004
		displayFolder: KPIs

	measure 'Medallas Oro' =
			COUNTROWS(FILTER(FACT_MEDALLA, FACT_MEDALLA[TIPO_MEDALLA] = "gold"))
		formatString: "#,##0"
		lineageTag: aa000001-0000-0000-0000-000000000005
		displayFolder: KPIs

	measure 'Medallas Plata' =
			COUNTROWS(FILTER(FACT_MEDALLA, FACT_MEDALLA[TIPO_MEDALLA] = "silver"))
		formatString: "#,##0"
		lineageTag: aa000001-0000-0000-0000-000000000006
		displayFolder: KPIs

	measure 'Medallas Bronce' =
			COUNTROWS(FILTER(FACT_MEDALLA, FACT_MEDALLA[TIPO_MEDALLA] = "bronze"))
		formatString: "#,##0"
		lineageTag: aa000001-0000-0000-0000-000000000007
		displayFolder: KPIs

	measure 'Edad Media' =
			AVERAGEX(
			    FACT_MEDALLA,
			    YEAR(DATE(2024, 7, 26)) - YEAR(FACT_MEDALLA[FECHA_NACIMIENTO])
			)
		formatString: "#,##0.0"
		lineageTag: aa000001-0000-0000-0000-000000000008
		displayFolder: KPIs

	measure '% Femenino' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_MEDALLA), FACT_MEDALLA[SEXO] = "female"),
			    COUNTROWS(FACT_MEDALLA),
			    0
			)
		formatString: "0.0%"
		lineageTag: aa000001-0000-0000-0000-000000000009
		displayFolder: KPIs

	measure 'Medallas / Atleta' =
			DIVIDE(
			    COUNTROWS(FACT_MEDALLA),
			    DISTINCTCOUNT(FACT_MEDALLA[ID_ATLETA]),
			    0
			)
		formatString: "#,##0.0"
		lineageTag: aa000001-0000-0000-0000-000000000010
		displayFolder: KPIs

	partition FACT_MEDALLA = m
		mode: import
		source =
				let
				    Origen = Snowflake.Databases("XKSHHPS-BG70575.snowflakecomputing.com","COMPUTE_WH",[Implementation="2.0"]),
				    GOLD_DB_DEV_Database = Origen{[Name="GOLD_DB_DEV",Kind="Database"]}[Data],
				    DBT_LGARCIADIAZ_Schema = GOLD_DB_DEV_Database{[Name="DBT_LGARCIADIAZ",Kind="Schema"]}[Data],
				    FACT_MEDALLA_Table = DBT_LGARCIADIAZ_Schema{[Name="FACT_MEDALLA",Kind="Table"]}[Data]
				in
				    FACT_MEDALLA_Table

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

